### ISSUE TITLE
Issue with json details file

### ISSUE THREAD

**Issue by dmaksimov** [zoho/zohocrm-typescript-sdk-6.0#3]
There looks to be an issue with the json details file.

It looks to be empty here: https://github.com/zoho/zohocrm-typescript-sdk-6.0/blob/50f2105cbd64534f27acce8d29422262eae4e657/config/json_details.json#L1

Noticed in the previous version it actually has some content. 

https://github.com/zoho/zohocrm-typescript-sdk-5.0/blob/717459ef6dd13629cbffe8249e46b67a336f12e0/config/json_details.json#L1

**Comment by raja-7453** [comment]
@dmaksimov Thank you for your contribution. The JSON file is more than 1MB it is not viewable in the GitHub UI, So you have to use "view raw".
